// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4949.WarehouseBot;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Solenoid pneumaticsExtendFork;
    public static Solenoid pneumaticsExtendGrips;
    public static Compressor pneumaticsCompressor;
    public static Relay pneumaticsPneumaticSpike;
    public static SpeedController driveTrainRightRear;
    public static SpeedController driveTrainLeftRear;
    public static SpeedController driveTrainLeftFront;
    public static SpeedController driveTrainRightFront;
    public static RobotDrive driveTrainRobotDrive41;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        pneumaticsExtendFork = new Solenoid(0, 1);
        LiveWindow.addActuator("Pneumatics", "Extend Fork", pneumaticsExtendFork);
        
        pneumaticsExtendGrips = new Solenoid(0, 0);
        LiveWindow.addActuator("Pneumatics", "Extend Grips", pneumaticsExtendGrips);
        
        pneumaticsCompressor = new Compressor(0);
                
        pneumaticsPneumaticSpike = new Relay(0);
        LiveWindow.addActuator("Pneumatics", "Pneumatic Spike", pneumaticsPneumaticSpike);
                 
        driveTrainLeftFront = new Victor(0);
        LiveWindow.addActuator("Drive Train", "LeftFront", (Victor) driveTrainLeftFront);

        driveTrainLeftRear = new Victor(1);
        LiveWindow.addActuator("Drive Train", "LeftRear", (Victor) driveTrainLeftRear);
        
        driveTrainRightFront = new Victor(2);
        LiveWindow.addActuator("Drive Train", "RightFront", (Victor) driveTrainRightFront);

        driveTrainRightRear = new Victor(3);
        LiveWindow.addActuator("Drive Train", "RightRear", (Victor) driveTrainRightRear);
      
        driveTrainRobotDrive41 = new RobotDrive(driveTrainLeftFront, driveTrainLeftRear,
              driveTrainRightFront, driveTrainRightRear);
        
        driveTrainRobotDrive41.setSafetyEnabled(true);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
